### PR TITLE
Added script that creates a random password

### LINKED ISSUE #400: Script to generate password

### PR DESCRIPTION
**Pull request by afeefaa333**
## Description

_Added script that creates a random password of user's desired length_ <br />

Fixes #400 

## Mentions

_afeefaa333_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings

### CODE REVIEW

**Comment by afeefaa333** [comment]
Why is it marked as spam!! I did actually contributed :-(
Please remove the 'spam' label...

**Comment by afeefaa333** [comment]
Please remove the label

**Comment by afeefaa333** [comment]
You marked me spam which may disqualify me for Hacktoberfest for no reason...
I am an enthusiastic open source contributor 
I earnestly request you  to remove the label, please.

**Comment by bartick** [comment]
I marked you spam because you didn't checked if this script was present or not. Its a general habit of a open source contributor to wait for a issue to be assigned before working on it. But you open the pull request without even waiting for us to assign it to you. 

Sorry, I deliberately marked you spam for not checkout the repo first before contributing.

**Comment by afeefaa333** [comment]
So sorry for contributing on the same topic. I did check the repo, but missed the existing solution.
Am a budding contributor, seems like good-first-issue went bad for me.
Going forward, will wait for an issue to be assigned before working on it.
But you marking me spam on Pull Request #395 too( where I did add a new solution) disqualifies me from  Hacktoberfest itself. 
( Any other label wouldn't have harmed so much )
Please let me be a part of Hacktoberfest.

**Comment by afeefaa333** [comment]
Still in hopes of being back in hacktoberfest

**Pull request closed without merging**
