### PR TITLE
Added a gui based multiplayer tic tac toe game

### LINKED ISSUE #291: TIC-TAC-TOE GUI Game
### Is your feature request related to a problem? Please describe
It would be a pygame module-based GUI game. With the help of the Alpha-Beta pruning algorithm of Artificial Intelligence, I'll make a player vs computer game.

### Describe the solution you'd like
Users/Players can play the game and while playing the game they can understand the concept of Alpha Beta pruning and how it works.

### Describe alternatives you've considered
Instead of Alpha-Beta pruning, I can also use the Mini-Max algorithm for the same.

### Additional context**
It would be user-friendly with a delightful UI.

### PR DESCRIPTION
**Pull request by invad3r07**
## Description
Created Tic Tac Toe python project made with gui using tkinter module 
Fixes #291 

## Dependencies

-No Dependencies

## Future Improvements

-Project is fully optimized but if any bug created. I would love to fix it

## Screenshots of relevant screen
image
image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by invad3r07** [comment]
Solved https://github.com/metafy-social/daily-python-scripts/issues/291

**Comment by invad3r07** [comment]
check & review @advaita-saha

**Comment by invad3r07** [comment]
Hey @agnxsh could you please tell me what exact problems did you faced??

**Comment by agnxsh** [comment]
This pr didn't have an issue linked, so we can score your pr accordingly, so first create an issue, then once you're assigned make the commit.

**Pull request closed without merging**
