### PR TITLE
Add HTML url to PDF converter

### LINKED ISSUE #44: HTML url to pdf script
I have PR-ed a simple script that lets you convert HTML url to pdf.

https://github.com/metafy-social/daily-python-scripts/pull/43

### PR DESCRIPTION
**Pull request by sarthakroy2002**
## Description

This is a simple script that lets you convert HTML url to pdf. <br />

Fixes #44 

## Dependencies

pdfkit and wkhtmltopdf

## Developer's checklist

- [ ✓] My PR follows the style guidelines of this project
- [✓ ] I have performed a self-check on my work

**If changes are made in the code:**

- [✓ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [✓ ] My changes in code generate no new warnings
- [✕ ] My changes are breaking another fix/feature of the project

### CODE REVIEW

**Review by advaita-saha — APPROVED** [review]
LGTM

**Comment by sarthakroy2002** [comment]
I have authenticated with https://hacktoberfest.auth.metafy.social/ but didnt receive any confirmation email. Maybe you can help :)

**Comment by advaita-saha** [comment]
> I have authenticated with https://hacktoberfest.auth.metafy.social/ but didnt receive any confirmation email. Maybe you can help :)

Hey you won't receive any email now, be rest assured your details have been registered in our server

**Comment by sarthakroy2002** [comment]
> > I have authenticated with https://hacktoberfest.auth.metafy.social/ but didnt receive any confirmation email. Maybe you can help :)
> 
> Hey you won't receive any email now, be rest assured your details have been registered in our server

ok Thanks

**Pull request merged**
