### PR TITLE
Add Android Open Source Project sync script

### PR DESCRIPTION
**Pull request by sarthakroy2002**
## Description

This is a basic script for Syncing the entire Android Open Source Project for building  <br />

## Developer's checklist

- [✓ ] My PR follows the style guidelines of this project
- [ ✓] I have performed a self-check on my work

**If changes are made in the code:**

- [ ✓] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [✓ ] My changes in code generate no new warnings
- [✕ ] My changes are breaking another fix/feature of the project

### CODE REVIEW

**Comment by advaita-saha** [comment]
There is no issue for this @sarthakroy2002

**Comment by sarthakroy2002** [comment]
Hey could you please remove the `spam` label :) I got 1 red flag from Hacktoberfest. @advaita-saha

**Comment by advaita-saha** [comment]
Please refrain from raising PRs without creating an issue first
Our team looses track of the contributions for these kind of acts, so these are penalties we have in place to maintain a smooth contribution process

**Comment by advaita-saha** [comment]
We are really sorry for your red flag, but our team is very particular about this, after a lot of spam PR influxed recently without raising any issues

**Pull request closed without merging**
