### PR TITLE
CMYK to RGB script added.

### LINKED ISSUE #155: CMYK To RGB Convertor
### Is your feature request related to a problem? Please describe
It would be handy to have a CMYK to RGB convertor to one when needed

### Describe the solution you'd like
You can go on the web and do the same, but I made a python script that makes its easier

### PR DESCRIPTION
**Pull request by biv720**
## Description

_A python-based CMYK to RGB converter has been added._ 

Fixes #155 

## Dependencies

_None_

## Future Improvements

_Adding RGB to CMYK_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [ ] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by biv720** [comment]
Hey, any issues with the PR?

**Comment by bartick** [comment]
The issue wasn't assigned to you. From the next time please only open PRs for the issues you are assigned for

**Comment by biv720** [comment]
> The issue wasn't assigned to you. From the next time please only open PRs for the issues you are assigned for

So, do I now close the PR and wait for the issue to be assigned? Follow Up, how do I ask for issue to be assigned to me?

**Review by bartick — APPROVED** [review]

**Comment by bartick** [comment]
Ok we will merge the PR. Please wait

**Pull request merged**
