### PR TITLE
Added python file for tracking product prices in Amazon

### LINKED ISSUE #204: Python project to track Amazon prices
### Is your feature request related to a problem? Please describe
I have often suffered while buying a product from amazon at right time and therefore want to make this project to solve my problem

### Describe the solution you'd like
Thy python app will keep track of amazon products and  send us mail when prices will go down.

### PR DESCRIPTION
**Pull request by ighoshsubho**
### Description
_Python project to track Amazon prices

Fixes #204 

- [*] My PR follows the style guidelines of this project

**If changes are made in the code:**

[*] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
[*] My changes in code generate no new warnings

 [ ] My changes are breaking another fix/feature of the project
 [ ] I have added test cases to show that my feature works
 [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Review by advaita-saha — CHANGES_REQUESTED** [review]
Please also create a readme within your script folder

**Comment by ighoshsubho** [comment]
*Ok i'll do that and create a PR tomorrow*

**Comment by bartick** [comment]
@ighoshsubho please don't create a new PR just push your changes in this PR

**Comment by raihankhan-rk** [comment]
@ighoshsubho the script contains smtplib module, but gmail has stopped support for 3rd party scripts. Kindly change either the module or the email provider.

**Comment by ighoshsubho** [comment]
@raihankhan-rk since this is a personal use project we can turn on the less secure apps option in gmail which ig will solve the above mentioned problem

**Comment by ighoshsubho** [comment]
ok @bartick I will push here

**Comment by raihankhan-rk** [comment]
@ighoshsubho gmail has stopped support for less secure apps. You can't do that anymore!

**Review by bartick — APPROVED** [review]

**Comment by ighoshsubho** [comment]
@raihankhan-rk let me do this with sendgrid, ig this can solve the problem

**Pull request merged**
