### PR TITLE
Create Locate Address

### LINKED ISSUE #54: Find the location of an IP address.
Sometimes you'll need to know the location of an IP address, whether it's your own or that of a site you're using.

One use-case for this is when you want to send login information to users for your website.

IHere we're going to see how you can find the location of an IP address using Python.

### PR DESCRIPTION
**Pull request by money8203**
## Description

- Locating an address can be useful if you're dealing with shipping or delivery logistics or for simple user-profiling tasks. To get started, install geocoder by running pip install geocoder in your terminal. The script below allows you to easily find the latitude and longitude coordinates for any address or to find an address from any set of coordinates:
Fixes #[ISSUENO]

## 

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Review by advaita-saha — CHANGES_REQUESTED** [review]
give filename and extension correctly
Your script should be under a folder with name of your project

Please also provide a readme for your script under your folder

Please complete these for your changes to get accepted

**Review by advaita-saha — CHANGES_REQUESTED** [review]
please make it a `.py` file

**Comment by money8203** [comment]
#62

**Comment by money8203** [comment]
please check #54 as i created a new file and new pull request.
Delete this one

**Pull request closed without merging**
