### PR TITLE
Get Location Information of an IP Address.

### PR DESCRIPTION
**Pull request by money8203**
## Description
Sometimes you'll need to know the location of an IP address, whether it's your own or that of a site you're using.

One use-case for this is when you want to send login information to users for your website.

IHere we're going to see how you can find the location of an IP address using Python.
## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works

### CODE REVIEW

**Comment by advaita-saha** [comment]
It is still not a `.py` file

**Review by advaita-saha — CHANGES_REQUESTED** [review]
please make it a .py file

**Comment by money8203** [comment]
Sorry, but i don't know how to convert into .py file since this is my 2nd project so could you please tell me how to do it !!

**Comment by advaita-saha** [comment]
Please link issue

**Comment by yunghog** [comment]
Im not getting the use case of this script. Using 2 APIs to get the information users already know. Do something like getting ip address as input and then using api to get its geolocation information.

**Pull request closed without merging**
