### PR TITLE
added screenshot

### LINKED ISSUE #7: Screenshots Tool
### Is your feature request related to a problem? Please describe
It's always handy to have an easy-to-use screenshot tool. 

### Describe the solution you'd like
Make an easy-to-use screenshot tool with all modern features like click a selected screen space. You can use modules like `pyscreenshot` to make the application.

### PR DESCRIPTION
**Pull request by ArshErgon**
regarding the issue  Fixes #7 
I have add the screenshot program.
I also add a .gitignore file

### CODE REVIEW

**Review by advaita-saha — CHANGES_REQUESTED** [review]
remove `.gitignore` from the repository

**Comment by ArshErgon** [comment]
hey @advaita-saha  can I ask why? `.gitignore` is file which we see in mostly every repos and we are using python which would produce pycache folders and some unnecessary files

**Comment by advaita-saha** [comment]
we understand the need of `.gitignore`
but we would be definetly adding that in few days covering most of the usecases. And since these PRs would be merged after Oct 1st, it's better to keep it removed @ArshErgon

**Comment by ArshErgon** [comment]
@advaita-saha understand, and its done, removed the `.gitignore` file

**Review by advaita-saha — APPROVED** [review]
LGTM 🚀

**Pull request merged**
