### PR TITLE
Added OpenCV Gray Image issue #117

### LINKED ISSUE #117: OpenCV Live Camera Preview
View Webcam With OpenCV and add features like Greyscale and Motion blur

### PR DESCRIPTION
**Pull request by AFZL210**
## Description

_Give a summary of the change that you have made_ <br />

Fixes #117 

## Dependencies

_Mention any dependencies/packages used_

## Future Improvements

_Mention any improvements to be done in future related to any file/feature_

## Mentions

_Mention and tag the people_

## Screenshots of relevant screens

_Add screenshots of relevant screens_

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [ ] My changes in code generate no new warnings
- [ ] My changes are breaking another fix/feature of the project
- [ ] I have added test cases to show that my feature works
- [ ] I have added relevant screenshots in my PR

### CODE REVIEW

**Review by advaita-saha — CHANGES_REQUESTED** [review]
Motion blur not implemented as said in issue #117

**Comment by AFZL210** [comment]
I'll add it

**Comment by AFZL210** [comment]
Added Blur To Image

**Review by advaita-saha — APPROVED** [review]
LGTM

**Pull request merged**
