### PR TITLE
Contributors list automated

### LINKED ISSUE #6: Enhance Documentation | README.md

### PR DESCRIPTION
**Pull request by aswin2108**
## Description
Added a new YAML file which will automate the contributor's list in the read me file.

Fixes #6 

## Mentions

@advaita-saha 

## Screenshots of relevant screens
image

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are not breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by agnxsh** [comment]
the code has been reviewed, is there any further feature? @aswin2108

**Comment by aswin2108** [comment]
@agnxsh No. This was the only one!

**Comment by agnxsh** [comment]
Okayyy

**Comment by aswin2108** [comment]
@agnxsh Can you add hacktoberfest accepted tag too??? For me in my profile its showing this repo is not participating!
image
Could you look into it???

**Comment by agnxsh** [comment]
sorry about that @aswin2108 now you're good to go

**Pull request merged**
