### PR TITLE
🚀 Added CLI and GUI password generator.

### LINKED ISSUE #1: Password Generator
### Is your feature request related to a problem? Please describe
With the new tech-boom and registration in multiple sites, people are running out of creating and managing unique passwords. Make a script, with a CLI which can be used to create unique password every time & also store them for later access.

### Describe the solution you'd like
Make a python script, with a CLI which can be used to create unique password every time & also store them for later access.

### PR DESCRIPTION
**Pull request by Montekkundan**
## Description

A Python3 script to generate a strong password.

Fixes #1  

## Dependencies

tkinter, pyperclip, random

## Mentions

@advaita-saha

## Screenshots of relevant screens
img_1

img

Untitled

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work
- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] I have added saved password results to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by advaita-saha** [comment]
you have added `.idea` folder since you were using pycharm
Please remove that

Also do authenticate yourself with the above mentioned link to be eligible for prizes

**Comment by Montekkundan** [comment]
> you have added `.idea` folder since you were using pycharm Please remove that
> 
> Also do authenticate yourself with the above mentioned link to be eligible for prizes

Okay im closing this pr and will remove the .idea folder.
Yup i did authenticate myself with my GitHub account.

**Comment by advaita-saha** [comment]
You don't need to open another PR
Just remove it in this one only

**Comment by Montekkundan** [comment]
✅ okay

**Comment by Montekkundan** [comment]
@advaita-saha How do I remove files from this pr 😅 doing this for the first time.

**Comment by Montekkundan** [comment]
okay phew i did it 😄.

**Comment by kriptonian1** [comment]
LGTM

**Review by advaita-saha — COMMENTED** [review]
LGTM

**Review by advaita-saha — APPROVED** [review]

**Pull request merged**
