### PR TITLE
added weather teller

### LINKED ISSUE #20: Weather teller
### Is your feature request related to a problem? 
A python script which can detect the weather of a place , just only by giving its name as input.

### Describe the solution you'd like
Add this script.

### Describe alternatives you've considered
None

### PR DESCRIPTION
**Pull request by srinjoy-26**
## Description

Added a script which can tell the weather of a place .

Fixes #20 

## Dependencies

pycharm , python 3.10 , weather API

## Future Improvements

detect weather

## Mentions

@advaita-saha 

## Screenshots of relevant screens

https://user-images.githubusercontent.com/91176055/193334348-1f690706-b7f1-470a-a69d-35f7de788814.mp4

## Developer's checklist

- [x] My PR follows the style guidelines of this project
- [x] I have performed a self-check on my work

**If changes are made in the code:**

- [x] I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
- [x] My changes in code generate no new warnings
- [x] My changes are breaking another fix/feature of the project
- [x] I have added test cases to show that my feature works
- [x] I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by agnxsh** [comment]
please hide your api keys @srinjoy-26  else we can't merge your pr

**Comment by srinjoy-26** [comment]
> please hide your api keys @srinjoy-26 else we can't merge your pr

Since I'm a beginner I'm unable to do it . Please consider and merge.

**Comment by agnxsh** [comment]
youtube mein dekh lo beta @srinjoy-26

**Comment by advaita-saha** [comment]
@srinjoy-26 
Sorry we cannot accept the PR due to security issues, and dependabots warnings

Please perform the aforesaid changes, so that we can merge it

**Pull request merged**
