### PR TITLE
Typing test

### LINKED ISSUE #4: Speed Typing Test
### Is your feature request related to a problem? Please describe
Create a program, test the typing speed of the user with a basic GUI application using Python language.

### Describe the solution you'd like
Make GUI based typing speed tester, which will show the speed of the user by word per minute

### PR DESCRIPTION
**Pull request by ArshErgon**
for the issue fixes #4 I have added the typing test program with GUI support, with README.md file also.

PS: I have created another branch for this PR but I dont know why its showing other branch code also.

### CODE REVIEW

**Comment by advaita-saha** [comment]
Will be reviewing soon
Till then do register yourself in https://hactoberfest.com

And DON'T FORGET TO AUTHENTICATE YOURSELF HERE : https://hacktoberfest.auth.metafy.social/

**Comment by advaita-saha** [comment]
Ok if you have registered once and seen a green tick, then you are registered

**Comment by advaita-saha** [comment]
Heyy sorry for the issue you are facing
Drop us an email with your GitHub id, email, name
at support@metafy.social

**Review by advaita-saha — CHANGES_REQUESTED** [review]
Screenshot is also here in this PR
Please remove that folder

**Comment by noobyysauraj** [comment]
> Ok if you have registered once and seen a green tick, then you are registered. You will only see the green tick the first time you register

Is this right place to query about the same thing? The web application only says I'm connected with github. Have to connect with discord too?

**Comment by advaita-saha** [comment]
> > Ok if you have registered once and seen a green tick, then you are registered. You will only see the green tick the first time you register
> 
> Is this right place to query about the same thing? The web application only says I'm connected with github. Have to connect with discord too?

Not necessarily, but we recommend doing so

**Comment by ArshErgon** [comment]
@advaita-saha yeah, the screenshot folder has been removed from the PR

**Review by advaita-saha — APPROVED** [review]
LGTM

**Pull request merged**
