### PR TITLE
Added URLShortener.py file

### LINKED ISSUE #5: URL Shortner Script
### Is your feature request related to a problem? Please describe
While sharing links from different websites, it gets pretty long and difficult to share and understand

### Describe the solution you'd like
Make a CLI based program that can take input of the link, and give a shortened version of the link. You are free to use any API which is FREE.

### Please comment your approach towards this, and we are happy to assign this to you

### PR DESCRIPTION
**Pull request by priddhesh**
Shortens the URL.

## Description

_It is CLI based program that can take URL as input from user and shorten it using **_pyshorteners_** python library_ <br />

Fixes #5 

## Dependencies

_1.**pyshorteners**
 2.**argparse**_

## Screenshots of relevant screens

_
image
_

## Developer's checklist

- My PR follows the style guidelines of this project
- I have performed a self-check on my work

**Acknowledgement:**

-  I have followed the [coding guidelines](https://google.github.io/styleguide/jsguide.html)
-  My changes in code generate no new warnings
-  I have added test cases to show that my feature works
-  I have added relevant screenshots in my PR

### CODE REVIEW

**Comment by bartick** [comment]
@priddhesh please mention the issue. So that people know that you have already raised a PR regarding that issue. Also its easier for us to track issues and PRs

**Comment by kriptonian1** [comment]
@priddhesh it's recommended to fill the fields in the PR, like description, screenshot, and others that are mentioned

**Comment by priddhesh** [comment]
@kriptonian1 I have made the necessary changes.Please review it.

**Comment by kriptonian1** [comment]
@priddhesh also add `requirements.txt` and try to document the code

**Review by advaita-saha — CHANGES_REQUESTED** [review]
Remove Image compressor file from this PR

**Comment by priddhesh** [comment]
@advaita-saha I have removed image compressor files from this PR. However, I am unable to raise new pr for image compression

**Review by advaita-saha — COMMENTED** [review]
LGTM

**Review by advaita-saha — COMMENTED** [review]
LGTM 🚀

**Comment by priddhesh** [comment]
@advaita-saha Can you explain what is LGTM?

**Review by advaita-saha — APPROVED** [review]
LGTM - Looks Good to Me

**Pull request merged**
